config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root "sessions#index"
  get "home", to: "sessions#index"
  get "select_org", to: "sessions#select_org"
  post "set_org", to: "sessions#set_org"
  post "connect", to: "sessions#create"
  get "disconnect", to: "sessions#destroy"
  get "dashboard", to: "dashboard#index"
  get "tasks/:id/:status", to: "tasks#update_task"
  get "poll_tasks", to: "tasks#poll_tasks"
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :require_fhir_client, :set_tasks

  # GET /dashboard
  def main
    @active_tab = active_tab
  end

  private

  # Getting all resources associated with the given patient

  def set_tasks
    success, result = fetch_tasks
    if success
      @active_tasks = result["active"] || []
      @completed_tasks = result["completed"] || []
      @cancelled_tasks = result["cancelled"] || []
    else
      flash[:warning] = result
    end
  end
end

app/views/dashboard/_ehr_tasks_table.html.erb
<div class="table-responsive small-text">
    <table class="table table-sm text-center table-fixed align-middle fw-semibold caption-top">
      <h3 class="text-secondary"><%= type.capitalize %> Tasks</h3>
        <thead class="text-center">
          <tr>
            <th scope="col">Request Date</th>
            <th scope="col">Task</th>
            <th scope="col">Priority</th>
            <th scope="col">Status</th>
            <th scope="col">Category</th>
            <th scope="col">Requester</th>
            <th scope="col">Patient</th>
            <th scope="col">Consent</th>
            <% if type == "completed" %>
              <th scope="col">Outcomes</th>
            <% end %>
            <% if type == "cancelled" || type == "rejected" %>
              <th scope="col">Reason</th>
            <% end %>
            <% if type == "active" %>
              <th scope="col">Actions</th>
            <% end %>
          </tr>
        </thead>
        <tbody>
          <% referrals.each do |referral| %>
            <tr id="task-row-<%= referral.id %>">
              <td><%= referral.authored_on %></td>
              <td>
                <% if referral.fhir_resource&.id.present? %>
                  <%= link_to referral.focus&.description, "#fhir-resource-modal-#{referral.id}", data: { bs_toggle: "modal" } %>
                  <% content_for :modals do %>
                    <%= render "shared/fhir_resource_modal", resource: referral.fhir_resource %>
                  <% end %>
                <% else %>
                  <%= referral.focus&.description|| "--"  %>
                <% end %>
              </td>
              <td><%= referral.focus&.priority || "-" %></td>
              <td>
                <% status = referral.status %>

                <% if status == "requested" %>
                  <span class="bi bi-arrow-90deg-right  text-primary"></span> Requested
                <% end %>
                <% if status == "in-progress" %>
                  <span class="bi bi-arrow-repeat text-success"></span> In Progress
                <% end %>
                <% if status == "completed" %>
                  <span class="bi bi-check-lg text-success"></span> Completed
                <% end %>
                <% if status == "cancelled" || status == "rejected" %>
                  <span class="bi bi-x-circle text-danger"></span><%= status.capitalize %>
                <% end %>

                <% if status == "accepted" %>
                  <span class="bi bi-check-circle text-success"></span> Accepted
                <% end %>
              </td>
              <td>
                <% if referral.focus&.fhir_resource&.id.present? %>
                  <%= link_to referral.focus&.category , "#fhir-resource-modal-#{referral.focus&.id}", data: { bs_toggle: "modal" } %>
                  <% content_for :modals do %>
                    <%= render "shared/fhir_resource_modal", resource: referral.focus&.fhir_resource %>
                  <% end %>
                <% else %>
                  <%= referral.focus&.category || "-" %>
                <% end %>
              </td>
              <td>

                <% if referral.requester_resource&.id.present? %>
                  <%= link_to referral.requester_name , "#fhir-resource-modal-#{referral.requester_resource&.id}", data: { bs_toggle: "modal" } %>
                  <% content_for :modals do %>
                    <%= render "shared/fhir_resource_modal", resource: referral.requester_resource %>
                  <% end %>
                <% else %>
                  <%= referral.requester_name %>
                <% end %>
              </td>
              <td>

                <% if referral.patient_resource&.id.present? %>
                  <%= link_to referral.patient_name, "#fhir-resource-modal-#{referral.patient_resource&.id}", data: { bs_toggle: "modal" } %>
                  <% content_for :modals do %>
                    <%= render "shared/fhir_resource_modal", resource: referral.patient_resource %>
                  <% end %>
                <% else %>
                  <%= referral.patient_name %>
                <% end %>
              </td>
              <td>
                <% if referral.consent.present? %>
                  <%= link_to referral.consent.code, "#fhir-resource-modal-#{referral.consent&.id}", data: { bs_toggle: "modal" } %>
                  <% content_for :modals do %>
                    <%= render "shared/fhir_resource_modal", resource: referral.consent.fhir_resource %>
                  <% end %>
                <% else %>
                  --
                <% end %>
              </td>
              <td>
                <% if type == "completed" %>

                  <% if referral.outcome&.id.present? %>
                     <%= link_to referral.outcome_type, "#referral-procedure-modal-#{referral.outcome&.id}", data: { bs_toggle: "modal" } %>
                    <% content_for :modals do %>
                      <%= render "dashboard/procedure_modal", resource: referral.outcome %>
                    <% end %>
                  <% else %>
                    --
                  <% end %>
                <% elsif type == "active" && referral.status == "requested" %>
                  <%= link_to "accept/reject", "#request-action-modal-#{referral.id}", data: { bs_toggle: "modal" } %>
                  <% content_for :modals do %>
                    <%= render "dashboard/request_action_modal", resource: referral, statuses: ["accepted", "rejected"] %>
                  <% end %>
                <% elsif type == "active" %>
                  <%= link_to "update task", "#request-action-modal-#{referral.id}", data: { bs_toggle: "modal" } %>
                  <% content_for :modals do %>
                    <%= render "dashboard/request_action_modal", resource: referral, statuses: ["in-progress", "cancelled", "completed"] %>
                  <% end %>
                <% elsif status == "rejected" || status == "cancelled" %>
                  <%= referral.status_reason || "--" %>
                <% else %>
                  --
                <% end %>
              </td>
          </tr>
        <% end %>
      </tbody>
    </table>
</div>

app/views/dashboard/_main_header.html.erb
<!-- app/views/dashboard/_main_header.html.erb -->

<header class="main-header py-2">
  <div class="container-fluid">
    <div class="row align-items-center justify-content-between">
      <div class="col-auto">
        <div class="logo-container">
          <a href="<%= root_path %>">
            <%= image_tag "logo.svg", class: "image", alt: "logo" %>
            <span class="name">CBO Application</span>
          </a>
        </div>
      </div>
      <div class="col-auto">
        <ul class="nav nav-tabs nav-fill mb-3" id="dashboardTabs" role="tablist">
          <%= render partial: "tab", locals: { id: "service-requests", label: "Service Requests", active: active_tab == "service-requests" } %>
          <%= render partial: "tab", locals: { id: "requesting-organizations", label: "Requesting Organizations", active: active_tab == "requesting-organizations" } %>
        </ul>
      </div>
      <div class="col-auto">
        <%= render "user_info" %>
      </div>
    </div>
  </div>
</header>

app/views/dashboard/_procedure_modal.html.erb
<div id="referral-procedure-modal-<%= resource.id %>" class="modal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title"> Outcome</h5></h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <div class="card">
          <div class="card-header">
            <h6 class="card-title">Procedure/<%= resource.id %></h6>
          </div>
          <div class="card-body">
            <div class="label-value">
              <span class="fw-semibold">Code:</span>
              <span class="small-text"><%= resource.description %></span>
            </div>
            <div class="label-value">
              <span class="fw-semibold">Category:</span>
              <span class="small-text"><%= resource.category%></span>
            </div>
            <div class="label-value">
              <span class="fw-semibold">Status:</span>
              <span class="small-text"><%= resource.status %></span>
            </div>
            <div class="label-value">
              <span class="fw-semibold">Performed Date:</span>
              <span class="small-text"><%= resource.performed_date&.to_date %></span>
            </div>
            <div class="label-value">
              <span class="fw-semibold">Addresses:</span>
              <span class="small-text">Condition/<%= resource.problem&.split("/").last %></span>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/dashboard/_request_action_modal.html.erb
<div id="request-action-modal-<%= resource.id %>" class="modal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title"><%= resource.status.capitalize %> Task</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <div class="card">
          <div class="card-header">
            <h6 class="card-title">ServiceRequest/<%= resource.focus&.id %></h6>
          </div>
          <div class="card-body">
            <!-- form with a GET method -->
            <%= form_with url: "/tasks/#{resource.id}/status", method: :get, id: "task-form-#{resource.id}", local: true do %>
              <div class="label-value">
                <span class="fw-semibold">Code:</span>
                <span class="small-text"><%= resource.focus&.description %></span>
              </div>
              <div class="label-value">
                <span class="fw-semibold">Category:</span>
                <span class="small-text"><%= resource.focus&.category%></span>
              </div>

              <div class="label-value">
                <span class="fw-semibold">Status:</span>
                <select name="task_status" class="form-select small-text" id="task_status-<%= resource.id %>">
                  <option value="">update the status</option>
                  <% statuses.each do |status| %>
                    <option value="<%= status %>"><%= status %></option>
                  <% end %>
                </select>
              </div>
              <div class="label-value status-reason-container" style="display:none;">
                <span class="fw-semibold">Status Reason:</span>
                <input type="text" name="status_reason" class="form-control small-text" id="status_reason-<%= resource.id %>">
              </div>



              <!-- submit button -->
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary">Submit</button>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  document.getElementById("task_status-<%= resource.id %>").addEventListener("change", function() {
    const statusReasonContainer = document.querySelector(".status-reason-container");
    if (this.value === "rejected" || this.value === "cancelled") {
      statusReasonContainer.style.display = "block";
    } else {
      statusReasonContainer.style.display = "none";
    }

  });
</script>

app/views/dashboard/_service_requests.html.erb
<!-- dashboard/_service_requests.html.erb -->

<div class="tab-pane fade <%= "show active" if active %>" id="<%= id %>" role="tabpanel" aria-labelledby="<%= id %>-tab">

  <% if @active_tasks.nil? && @completed_tasks.nil? && @cancelled_tasks.nil? %>
    <h5 class="text-muted text-center my-3"> There no requests yet</h5>
  <% else %>
    <div class="table-wrapper y-3 px-3 border-bottom">
      <div id="active-tasks-table">
        <%= render "tasks_table", referrals: @active_tasks, type: "active" %>
      </div>
    </div>
    <div class="table-wrapper my-5 px-3 border-bottom">
      <div id="completed-tasks-table">
        <%= render "tasks_table", referrals: @completed_tasks, type: "completed" %>
      </div>
    </div>
    <div class="table-wrapper mt-5 px-3">
      <div id="cancelled-tasks-table">
        <%= render "tasks_table", referrals: @cancelled_tasks, type: "cancelled" %>
      </div>
    </div>
  <% end %>

</div>

app/views/dashboard/_tab.html.erb
<!-- app/views/dashboard/_tab.html.erb -->

<li class="nav-item" role="presentation">
  <a class="nav-link <%= 'active' if active %> menu-tab d-flex" id="<%= id %>-tab" data-bs-toggle="tab" href="#<%= id %>" role="tab" aria-controls="<%= id %>" aria-selected="<%= active %>" data-controller="notifications">
    <%= label %>
    <div class="dropdown">
      <span class="badge bg-primary ms-2 dropdown-toggle" id="<%= id %>-notification-count" style="display:none;" data-bs-toggle="dropdown" aria-expanded="false"></span>
      <ul class="dropdown-menu" id="<%= id %>-notification-dropdown" aria-labelledby="<%= id %>-notification-count">
      </ul>
    </div>
  </a>
</li>

app/views/dashboard/_tabs.html.erb
<!-- app/views/dashboard/_tabs.html.erb -->

<div data-controller="poll-tasks" data-poll-url="<%= fhir_client_connected? ? poll_tasks_path : "" %>">
  <div class="tab-content mt-2">
    <%= render partial: "service_requests", locals: { id: "service-requests", active: active_tab == "service-requests" } %>
    <%= render partial: "requesting_organizations", locals: { id: "requesting-organizations", active: active_tab == "requesting-organizations" } %>

  </div>
</div>

app/views/dashboard/_tasks_table.html.erb
<div class="table-responsive small-text">
    <table class="table table-sm text-center table-fixed align-middle fw-semibold caption-top">
      <h3 class="text-secondary"><%= type.capitalize %> Tasks</h3>
        <thead class="text-center">
          <tr>
            <th scope="col">Request Date</th>
            <th scope="col">Task</th>
            <th scope="col">Priority</th>
            <th scope="col">Status</th>
            <th scope="col">Category</th>
            <th scope="col">Requester</th>
            <th scope="col">Patient</th>
            <th scope="col">Consent</th>
            <% if type == "completed" %>
              <th scope="col">Outcomes</th>
            <% end %>
            <% if type == "cancelled" || type == "rejected" %>
              <th scope="col">Reason</th>
            <% end %>
            <% if type == "active" %>
              <th scope="col">Actions</th>
            <% end %>
          </tr>
        </thead>
        <tbody>
          <% referrals.each do |referral| %>
            <tr id="task-row-<%= referral.id %>">
              <td><%= referral.authored_on %></td>
              <td>
                <% if referral.fhir_resource&.id.present? %>
                  <%= link_to referral.focus&.description, "#fhir-resource-modal-#{referral.id}", data: { bs_toggle: "modal" } %>
                  <% content_for :modals do %>
                    <%= render "shared/fhir_resource_modal", resource: referral.fhir_resource %>
                  <% end %>
                <% else %>
                  <%= referral.focus&.description|| "--"  %>
                <% end %>
              </td>
              <td><%= referral.focus&.priority || "-" %></td>
              <td>
                <% status = referral.status %>

                <% if status == "requested" %>
                  <span class="bi bi-arrow-90deg-right  text-primary"></span> Requested
                <% end %>
                <% if status == "in-progress" %>
                  <span class="bi bi-arrow-repeat text-success"></span> In Progress
                <% end %>
                <% if status == "completed" %>
                  <span class="bi bi-check-lg text-success"></span> Completed
                <% end %>
                <% if status == "cancelled" || status == "rejected" %>
                  <span class="bi bi-x-circle text-danger"></span><%= status.capitalize %>
                <% end %>

                <% if status == "accepted" %>
                  <span class="bi bi-check-circle text-success"></span> Accepted
                <% end %>
              </td>
              <td>
                <% if referral.focus&.fhir_resource&.id.present? %>
                  <%= link_to referral.focus&.category , "#fhir-resource-modal-#{referral.focus&.id}", data: { bs_toggle: "modal" } %>
                  <% content_for :modals do %>
                    <%= render "shared/fhir_resource_modal", resource: referral.focus&.fhir_resource %>
                  <% end %>
                <% else %>
                  <%= referral.focus&.category || "-" %>
                <% end %>
              </td>
              <td>

                <% if referral.requester_resource&.id.present? %>
                  <%= link_to referral.requester_name , "#fhir-resource-modal-#{referral.requester_resource&.id}", data: { bs_toggle: "modal" } %>
                  <% content_for :modals do %>
                    <%= render "shared/fhir_resource_modal", resource: referral.requester_resource %>
                  <% end %>
                <% else %>
                  <%= referral.requester_name %>
                <% end %>
              </td>
              <td>

                <% if referral.patient_resource&.id.present? %>
                  <%= link_to referral.patient_name, "#fhir-resource-modal-#{referral.patient_resource&.id}", data: { bs_toggle: "modal" } %>
                  <% content_for :modals do %>
                    <%= render "shared/fhir_resource_modal", resource: referral.patient_resource %>
                  <% end %>
                <% else %>
                  <%= referral.patient_name %>
                <% end %>
              </td>
              <td>
                <% if referral.consent.present? %>
                  <%= link_to referral.consent.code, "#fhir-resource-modal-#{referral.consent&.id}", data: { bs_toggle: "modal" } %>
                  <% content_for :modals do %>
                    <%= render "shared/fhir_resource_modal", resource: referral.consent.fhir_resource %>
                  <% end %>
                <% else %>
                  --
                <% end %>
              </td>
              <td>
                <% if type == "completed" %>

                  <% if referral.outcome&.id.present? %>
                     <%= link_to referral.outcome_type, "#referral-procedure-modal-#{referral.outcome&.id}", data: { bs_toggle: "modal" } %>
                    <% content_for :modals do %>
                      <%= render "dashboard/procedure_modal", resource: referral.outcome %>
                    <% end %>
                  <% else %>
                    --
                  <% end %>
                <% elsif type == "active" && referral.status == "requested" %>
                  <%= link_to "accept/reject", "#request-action-modal-#{referral.id}", data: { bs_toggle: "modal" } %>
                  <% content_for :modals do %>
                    <%= render "dashboard/request_action_modal", resource: referral, statuses: ["accepted", "rejected"] %>
                  <% end %>
                <% elsif type == "active" %>
                  <%= link_to "update task", "#request-action-modal-#{referral.id}", data: { bs_toggle: "modal" } %>
                  <% content_for :modals do %>
                    <%= render "dashboard/request_action_modal", resource: referral, statuses: ["in-progress", "cancelled", "completed"] %>
                  <% end %>
                <% elsif status == "rejected" || status == "cancelled" %>
                  <%= referral.status_reason || "--" %>
                <% else %>
                  --
                <% end %>
              </td>
          </tr>
        <% end %>
      </tbody>
    </table>
</div>

app/views/dashboard/_user_info.html.erb
<div class="user-info">
  <div class="dropdown">
    <div class="avatar dropdown-toggle" id="avatarDropdown" data-bs-toggle="dropdown" aria-expanded="false">
      <img src="<%= asset_path("avatar.svg") %>" alt="avatar" class="image">
    </div>
    <ul class="dropdown-menu" aria-labelledby="avatarDropdown">
      <li><a class="dropdown-item" href="/disconnect">Logout</a></li>
    </ul>
  </div>
  <div class="details">
    <span class="name"><%= @current_user&.name || "Test User" %></span>
  </div>
</div>

app/views/dashboard/index.html.erb
<!--app/views/dashboard/main.html.erb -->

<%= render 'main_header' %>
<%= render 'tabs' %>